/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Servidor.Controlclientes;

/**
 *
 * @author Manuel Montoya
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    Controlclientes c;
    String nom;
    ClienteprivGUI cp;
    ClientegrupoGUI cg;
    
    public Menu() {
        initComponents();
        c = null;
        cp = null;
        cg = null;
    }
    
    public void setNombre(String nom){
    this.nom = nom;
    }
    
    public void setCoontrolclientes(Controlclientes c){
    this.c = c;
    
    }
    public void setClientegrupo(ClientegrupoGUI cg){
    this.cg = cg;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clientep = new javax.swing.JButton();
        clienteg = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jLabelMsjP = new javax.swing.JLabel();
        jLabelMsjG = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        clientep.setText("Privado");
        clientep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientepActionPerformed(evt);
            }
        });

        clienteg.setText("Grupo");
        clienteg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientegActionPerformed(evt);
            }
        });

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        jLabelMsjP.setText("Mensajes 0");

        jLabelMsjG.setText("Mensajes 0");

        jLabelUsuario.setText("Usuarios");

        jLabel1.setText("Menu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelUsuario)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clientep)
                            .addComponent(jLabelMsjP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clienteg)
                            .addComponent(jLabelMsjG))
                        .addGap(32, 32, 32))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(169, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(salir))
                .addGap(178, 178, 178))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jLabelUsuario)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMsjP)
                    .addComponent(jLabelMsjG))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientep)
                    .addComponent(clienteg))
                .addGap(32, 32, 32)
                .addComponent(salir)
                .addGap(69, 69, 69))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clientepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientepActionPerformed
     cp.setNombre(nom);
        cp.setjLabelUsuario(nom);
        c.setContadorP(0);
        jLabelMsjP.setText(c.getContadorP() + " Nuevos Mensajes");
        cp.setVisible(true);
    }//GEN-LAST:event_clientepActionPerformed

    private void clientegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientegActionPerformed
        cg.setNombre(nom);
        cg.setjLabelUsuario(nom);
        c.setContadorG(0);
        jLabelMsjG.setText(c.getContadorG() + " Nuevos Mensajes");
        cg.setVisible(true);
    }//GEN-LAST:event_clientegActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        this.c.enviarOpcion("$EXIT$");
        this.c.enviarOpcionGrupo("$EXIT$");
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

   

    void setJLabelUsuario(String text) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clienteg;
    private javax.swing.JButton clientep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelMsjG;
    private javax.swing.JLabel jLabelMsjP;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
